CartApp/urls.py
from django.urls import path

from CartApp import views

app_name = 'CartApp'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('add-to-cart/', views.AddToCart.as_view(), name='add_to_cart'),
    path('remove-product/', views.RemoveProduct.as_view(), name='remove_product'),
    path('empty-cart/', views.EmptyCart.as_view(), name='empty_cart'),
    path('update-count/', views.UpdateCount.as_view(), name='update_count'),
    path('checkout/', views.Checkout.as_view(), name='checkout'),
    path('request/', views.SendRequest.as_view(), name='request'),
    path('verify/', views.Verify.as_view(), name='verify'),
]

ProductsApp/urls.py
from django.urls import path

from ProductsApp import views

app_name = 'ProductsApp'

urlpatterns = [
    path('product-detail/<int:product_id>/', views.product_detail, name='product_detail'),
    path('product-list/', views.ProductListView.as_view(), name='product_list'),
    path('product-list/category/<str:category>/', views.ProductListView.as_view(), name='products_by_category'),
    path('product-list/brand/<str:brand>/', views.ProductListView.as_view(), name='products_by_brand'),
    path('product-color-stock/', views.color_stock, name='product_color_stock'),
    path('add-comment/', views.product_comment, name='product_comment'),
    path('delete-comment/', views.delete_comment, name='delete_comment'),
    path('add-favorite/', views.add_product_to_favorite, name='add_product_to_favorite'),
    path('add-rate/', views.add_rate, name='add_rate'),
]

UserApp/urls.py
from django.urls import path

from UserApp import views
from django.contrib.auth import views as auth_views

app_name = 'UserApp'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('password-reset/', auth_views.PasswordResetView.as_view(success_url='done'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url='/password-reset/complete'),
         name="password_reset_confirm"),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('profile/', views.user_profile, name='profile'),
    path('favorite-products/', views.favorite_products, name='favorite_products'),
    path('addresses/', views.addresses, name='addresses'),
    path('factors/', views.factors, name='factors'),
    path('get-city/', views.get_city, name='get_city'),
    path('add-address/', views.add_address, name='add_address'),
    path('delete-address/', views.delete_address, name='delete_address'),
    path('activate-address/', views.activate_address, name='activate_address'),
    path('edit-address/', views.edit_address, name='edit_address')
]

CartApp/models.py
from django.db import models

from ProductsApp.models import Product
from UserApp.models import User, Address


# Create your models here.

class CartModel(models.Model):
    status = [
        ('در انتظار پرداخت', 'در انتظار پرداخت'),
        ('پرداخت شده', 'پرداخت شده'),
        ('ارسال شده', 'ارسال شده'),
        ('تکمیل شده', 'تکمیل شده'),
    ]
    cart_random_number = models.CharField(max_length=10, unique=True, blank=True, verbose_name='شماره سفارش')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, verbose_name='آدرس', null=True, blank=True)
    status = models.CharField(max_length=25, default='در انتظار پرداخت', choices=status, verbose_name='وضعیت')
    final_price = models.PositiveIntegerField(default=0, verbose_name='مبلغ')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')
    authority = models.CharField(max_length=50, null=True, blank=True, verbose_name='شماره تراکنش')
    payment_date = models.DateTimeField(null=True, blank=True, verbose_name='تاریخ پرداخت')
    delivery_date = models.DateTimeField(null=True, blank=True, verbose_name='تاریخ ارسال')

    class Meta:
        verbose_name = 'سفارش'
        verbose_name_plural = 'سفارشات'

    def __str__(self):
        return f'Cart {self.id}'

    def save(self, *args, **kwargs):
        if not self.cart_random_number:
            import random
            self.cart_random_number = ''.join(random.choices('0123456789', k=10))
        super(CartModel, self).save(*args, **kwargs)


class CartItem(models.Model):
    cart = models.ForeignKey(CartModel, on_delete=models.CASCADE, related_name='items', verbose_name='سفارش')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='محصول')
    color_id = models.PositiveIntegerField(verbose_name='id رنگ')
    price = models.PositiveIntegerField(verbose_name='قیمت')
    final_price = models.PositiveIntegerField(verbose_name='قیمت کل')
    color = models.CharField(max_length=10, verbose_name='رنگ')
    color_stock = models.IntegerField(verbose_name='موجودی رنگ')
    weight = models.IntegerField(verbose_name='وزن')
    quantity = models.IntegerField(default=1, verbose_name='تعداد')

    class Meta:
        verbose_name = 'آیتم سفارش'
        verbose_name_plural = 'آیتم های سفارش'

    def __str__(self):
        return f'Cart {self.cart.id} Item {self.id}'

    def get_post_price(self):
        cart = self.cart
        products = cart.items.all()
        total_price = 0
        for product in products:
            total_price += product.final_price
        return total_price

CartApp/views.py
from django.conf import settings
import requests
import json
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views import View
from CartApp.cart import Cart
from CartApp.models import CartModel


# Create your views here.

class AddToCart(View):
    def get(self, request):
        try:
            product_id = request.GET.get('product_id')
            product_color_id = request.GET.get('color_id')
            if not product_color_id:
                return JsonResponse({'status': "color_id"})
            count = request.GET.get('count')
            cart = Cart(request)
            cart.add(product_id, product_color_id, count, user=request.user)
            cart_count = cart.count()
            response = {
                'cart_count': cart_count,
                'status': True
            }
            return JsonResponse(response)
        except:
            return JsonResponse({'status': False})


class CartView(View):
    template_name = 'cart_app/cart.html'

    def get(self, request):
        cart = Cart(request)
        for item in cart.__iter__(include_product=False):
            cart.add(item['id'], item['color_id'], user=request.user)
        return render(request, self.template_name, {'cart': cart})


def cart_products(request):
    cart = Cart(request)
    return render(request, 'partials/cart-partial.html', {'cart': cart})


def cart_prices(request):
    cart = Cart(request)
    return render(request, 'partials/price-partial.html', {'cart': cart})


class EmptyCart(View):
    template_name = 'partials/cart-partial.html'

    def get(self, request):
        cart = Cart(request)
        cart = cart.clear(request.user)
        html = render(request, self.template_name, {'cart': cart})
        response = {
            'html': html.content.decode('utf-8'),
            'cart_count': '0'
        }
        return JsonResponse(response)


class RemoveProduct(View):
    template_name = 'partials/cart-partial.html'

    def get(self, request):
        product_id = request.GET.get('product_id')
        color_id = request.GET.get('color_id')
        cart = Cart(request)
        cart.remove(product_id, color_id, request.user)
        html = render(request, self.template_name, {'cart': cart})
        response = {
            'html': html.content.decode('utf-8'),
            'cart_count': cart.count()
        }
        return JsonResponse(response)


class UpdateCount(View):
    template_name = 'partials/price-partial.html'

    def get(self, request):
        update_type = request.GET.get('type')
        product_id = request.GET.get('product_id')
        color_id = request.GET.get('color_id')
        cart = Cart(request)
        if update_type == 'increase':
            cart.increase(product_id, color_id, request.user)
        elif update_type == 'decrease':
            cart.decrease(product_id, color_id, request.user)
        html = render(request, self.template_name, {'cart': cart})
        off_price = cart.get_off_price(product_id, color_id)
        final_price = cart.get_final_price(product_id, color_id)
        cart_count = cart.count()
        response = {
            'off_price': off_price,
            'final_price': final_price,
            'html': html.content.decode('utf-8'),
            'cart_count': cart_count
        }
        return JsonResponse(response)


class Checkout(LoginRequiredMixin, View):
    template_name = 'cart_app/checkout.html'

    def get(self, request):
        cart = Cart(request)
        active_address = request.user.addresses.filter(is_active=True).first()
        context = {
            'cart': cart,
            'active_address': active_address
        }
        return render(request, self.template_name, context)


class SendRequest(LoginRequiredMixin, View):
    def get(self, request):
        cart = Cart(request)
        amount = cart.get_payable_price() * 10
        data = {
            "MerchantID": settings.MERCHANT,
            "Amount": amount,
            "Description": settings.DESCRIPTION,
            "CallbackURL": settings.CALLBACKURL,
        }
        data = json.dumps(data)
        # set content length by data
        headers = {'content-type': 'application/json', 'content-length': str(len(data))}
        try:
            response = requests.post(settings.ZP_API_REQUEST, data=data, headers=headers, timeout=10)
            if response.status_code == 200:
                response_data = response.json()
                if response_data['Status'] == 100:
                    return redirect(settings.ZP_API_STARTPAY + response_data['Authority'])
                else:
                    return JsonResponse({'status': False, 'code': str(response_data['Status'])})
            return JsonResponse({'status': False, 'code': str(response.status_code)})
        except requests.exceptions.Timeout:
            return JsonResponse({'status': False, 'code': 'timeout'})
        except requests.exceptions.ConnectionError:
            return JsonResponse({'status': False, 'code': 'connection error'})


class Verify(LoginRequiredMixin, View):
    template_name = 'cart_app/payment-confirm.html'

    def get(self, request):
        cart = Cart(request)
        amount = cart.get_payable_price() * 10
        authority = request.GET['Authority']
        data = {
            "MerchantID": settings.MERCHANT,
            "Amount": amount,
            "Authority": authority,
        }
        data = json.dumps(data)
        # set content length by data
        headers = {'content-type': 'application/json', 'content-length': str(len(data))}
        response = requests.post(settings.ZP_API_VERIFY, data=data, headers=headers)

        if response.status_code == 200:
            status = request.GET['Status']
            authority = request.GET['Authority']
            if status == 'OK':
                cart = Cart(request)
                cart.clear()
                cart_model = CartModel.objects.filter(user=request.user, status='در انتظار پرداخت').first()
                cart_model.status = 'پرداخت شده'
                cart_model.payment_date = timezone.now()
                cart_model.authority = authority
                cart_model.save()
                context = {
                    'cart': cart_model,
                    'payment': True
                }
                return render(request, self.template_name, context)
            else:
                return redirect('CartApp:cart')
        return redirect('CartApp:cart')

CartApp/templates/partials/cart-partial.html
{% load render_partial %}
{% load product_tags %}
{% load humanize %}
{% load base %}
<div class="content">
    <div class="row">
        <div class="col-12 col-lg-9">
            <div id="cart-products">
                <div class="container">
                    <div class="row">
                        <div class="col-12 py-3">
                            <div class="pb-3" id="return-to-shop">می‌خواهید محصولات دیگری اضافه
                                کنید؟ <a href="products.html">بازگشت به فروشگاه</a></div>
                            <div id="products-cont" class="d-none d-md-block">
                                <div class="row my-2" id="heading">
                                    <div class="col-4">
                                        <div>کالا</div>
                                    </div>
                                    <div class="col-2">
                                        <div>قیمت واحد</div>
                                    </div>
                                    <div class="col-2 pl-4">
                                        <div>تعداد</div>
                                    </div>
                                    <div class="col-2">
                                        <div>تخفیف</div>
                                    </div>
                                    <div class="col-2 pr-0">
                                        <div class="pr-3">قیمت نهایی</div>
                                    </div>
                                </div>
                            </div>

                            {% for item in cart %}
                                <div class="row product" data-product-id="{{ item.product.id }}"
                                     data-color-id="{{ item.color_id }}">
                                    <div class="col-12 col-md-4">
                                        <div class="row">
                                            <div class="col-2 col-md-4 pl-0">
                                                <img src="{{ item.product|product_main_image }}"
                                                     alt={{ item.product.title }}"">
                                            </div>
                                            <div class="col-10 col-md-8">
                                                <a href="{% url 'ProductsApp:product_detail' item.product.id %}"
                                                   target="_blank">
                                                    <div class="title pt-2">{{ item.product.title }}<span
                                                            class="btn border border-3 rounded-circle"
                                                            style="background-color: {{ item.color }}"></span>
                                                    </div>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-6 col-md-2">
                                        <div class="d-md-none font-weight-bold">قیمت</div>
                                        <div class="pt-1"><span
                                                id="one-price"
                                                class="product-encode4365gbf265g43d">{{ item.product.price|intcomma:False }}</span>
                                            <span>تومان</span></div>
                                    </div>
                                    <div class="col-6 col-md-2 pl-4 pr-0 pr-md-3">
                                        <div class="d-md-none font-weight-bold">تعداد</div>
                                        <div class="input-group mb-3 order-number">
                                            <div class="input-group-prepend">
                                                <button onclick="updateCount('increase')"
                                                        class="btn btn-outline-secondary btn-plus"
                                                        type="button">+
                                                </button>
                                            </div>
                                            <input oninput="enforceMinMax(this)" type="number" name="order-number[]"
                                                   value="{{ item.quantity }}"
                                                   class="form-control text-center order-number number-input"
                                                   readonly min="0" max="{{ item.color_stock }}">
                                            <div class="input-group-prepend">
                                                <button onclick="updateCount('decrease')"
                                                        class="btn btn-outline-secondary btn-minus"
                                                        type="button">_
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-6 col-md-2">
                                        <div class="d-md-none font-weight-bold">تخفیف</div>
                                        <div>
                                            <span id="off-price">{{ item.product.off_price|multiply:item.quantity|intcomma:False }}</span>
                                            <span>تومان</span>
                                        </div>
                                    </div>
                                    <div class="col-6 col-md-2 pr-0">
                                        <div class="d-md-none font-weight-bold">قیمت نهایی</div>
                                        <div class="pt-1 pr-2 bg-light"><span
                                                id="final-price"
                                                class="product-total">{{ item.product.final_price|multiply:item.quantity|intcomma:False }}</span>
                                            <span>تومان</span></div>
                                        <a onclick="removeProduct()"
                                           class="product-remove btn-remove-from-basket w-auto send-reply"
                                           data-product-id="{{ item.product.id }}" data-color-id="{{ item.color_id }}">
                                            <div class="small pl-2"><i class="fa fa-times"></i> حذف
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            {% empty %}
                                <div class="col-12 alert alert-warning">محصولی در سبد خرید شما وجود
                                    ندارد.
                                </div>
                            {% endfor %}

                            <div class="row">
                                <div class="col-12">
                                    <a onclick="emptyCart()"
                                       class="product-remove btn-remove-from-basket send-reply"
                                       data-id="all">
                                        <div class="float-end small pl-2 font-weight-bold">خالی کردن
                                            سبد
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-3 mt-2 mt-lg-0 pr-3 pr-lg-0">
            <div id="factor">
                {% render_partial 'CartApp.views.cart_prices' %}
            </div>
        </div>
    </div>
</div>

CartApp/templates/partials/price-partial.html
{% load humanize %}
<div class="container">
    <div class="row py-2">
        <div class="col-6">
            <div>جمع قیمت محصولات:</div>
        </div>
        <div class="col-6">
            <div><span
                    id="factor-total-encode4365gbf265g43d">{{ cart.get_products_price|intcomma:False|default:0 }}</span>
                تومان
            </div>
        </div>
    </div>
    <div class="row py-2">
        <div class="col-6">
            <div>هزینه ی ارسال:</div>
        </div>
        <div class="col-6">
            <div><span
                    id="factor-total-encode4365gbf265g43d">{{ cart.get_post_price|intcomma:False|default:0 }}</span>
                تومان
            </div>
        </div>
    </div>
    <div class="row py-2">
        <div class="col-6">
            <div>جمع کل فاکتور:</div>
        </div>
        <div class="col-6">
            <div><span
                    id="factor-total-encode4365gbf265g43d">{{ cart.get_total_final_price|intcomma:False|default:0 }}</span>
                تومان
            </div>
        </div>
    </div>
    <div class="row py-2 bg-light">
        <div class="col-6">
            <div>جمع تخفیف:</div>
        </div>
        <div class="col-6">
            <div><span class="text-danger"
                       id="factor-total-discount">{{ cart.get_total_off_price|intcomma:False|default:0 }}</span>
                تومان
            </div>
        </div>
    </div>
    <div class="row py-2" id="total">
        <div class="col-6">
            <div>مبلغ قابل پرداخت:</div>
        </div>
        <div class="col-6">
            <div><span
                    id="factor-total">{{ cart.get_payable_price|intcomma:False|default:0 }}</span>
                تومان
            </div>
        </div>
    </div>
    <div class="row py-2">
        <div class="col-12">
            {% if request.user.is_authenticated %}
            	<a href="{% url 'CartApp:checkout' %}"><input type="submit" value="ادامه ثبت سفارش"
                                           class="btn btn-success w-100"></a>
            {% else %}
                <p>برای ادامه فرآیند خرید باید ثبت نام کنید </p><a href="{% url 'UserApp:login' %}">ثبت نام/ورود</a>
            {% endif %}

        </div>
    </div>
</div>