CartApp/urls.py
from django.urls import path

from CartApp import views

app_name = 'CartApp'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('add-to-cart/', views.AddToCart.as_view(), name='add_to_cart'),
    path('remove-product/', views.RemoveProduct.as_view(), name='remove_product'),
    path('empty-cart/', views.EmptyCart.as_view(), name='empty_cart'),
    path('update-count/', views.UpdateCount.as_view(), name='update_count'),
    path('checkout/', views.Checkout.as_view(), name='checkout'),
    path('request/', views.SendRequest.as_view(), name='request'),
    path('verify/', views.Verify.as_view(), name='verify'),
]

IndexApp/urls.py
from django.urls import path

from IndexApp import views

app_name = 'IndexApp'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('about-us/', views.AboutUs.as_view(), name='about_us'),
    path('search/', views.Search.as_view(), name='search'),
]

ProductsApp/urls.py
from django.urls import path

from ProductsApp import views

app_name = 'ProductsApp'

urlpatterns = [
    path('product-detail/<int:product_id>/', views.product_detail, name='product_detail'),
    path('product-list/', views.ProductListView.as_view(), name='product_list'),
    path('product-list/category/<str:category>/', views.ProductListView.as_view(), name='products_by_category'),
    path('product-list/brand/<str:brand>/', views.ProductListView.as_view(), name='products_by_brand'),
    path('product-color-stock/', views.color_stock, name='product_color_stock'),
    path('add-comment/', views.product_comment, name='product_comment'),
    path('delete-comment/', views.delete_comment, name='delete_comment'),
    path('add-favorite/', views.add_product_to_favorite, name='add_product_to_favorite'),
    path('add-rate/', views.add_rate, name='add_rate'),
]

UserApp/urls.py
from django.urls import path

from UserApp import views
from django.contrib.auth import views as auth_views

app_name = 'UserApp'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('password-reset/', auth_views.PasswordResetView.as_view(success_url='done'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url='/password-reset/complete'),
         name="password_reset_confirm"),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('profile/', views.user_profile, name='profile'),
    path('favorite-products/', views.favorite_products, name='favorite_products'),
    path('addresses/', views.addresses, name='addresses'),
    path('factors/', views.factors, name='factors'),
    path('get-city/', views.get_city, name='get_city'),
    path('add-address/', views.add_address, name='add_address'),
    path('delete-address/', views.delete_address, name='delete_address'),
    path('activate-address/', views.activate_address, name='activate_address'),
    path('edit-address/', views.edit_address, name='edit_address')
]

templates/infinite shop/partial/footer.html
{% load static %}
<section class="pt-4 pb-3" id="footer">
    <div class="container">
        <div class="row">
            <div class="col-6 col-sm-4 col-lg-2">
                <div class="title">دسترسی کاربر</div>
                <ul>
                    {% if not request.user.is_authenticated %}
                        <li><a href="{% url 'UserApp:login' %}">ورود</a></li>
                        <li><a href="{% url 'UserApp:register' %}">ثبت نام</a></li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'UserApp:profile' %}">پروفایل</a></li>
                    {% endif %}
                    <li><a href="{% url 'UserApp:factors' %}">لیست سفارش ها</a></li>
                    <li><a href="{% url 'UserApp:favorite_products' %}">محصولات مورد علاقه</a></li>
                    <li><a href="{% url 'UserApp:addresses' %}">آدرس ها</a></li>
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'UserApp:logout' %}">خروج</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-6 col-sm-4 col-lg-2">
                <div class="title">دسته بندی محصولات</div>
                <ul>
                    {% for main_category in main_categories %}
                        <li><a href="{% url 'ProductsApp:products_by_category' main_category.url_title %}">{{ main_category.title }}</a></li>
                    {% endfor %}
                    
                </ul>
            </div>
            <div class="col-6 col-sm-4 col-lg-2">
                <div class="title">دسترسی سریع</div>
                <ul>
                    <li ><a href="{% url 'CartApp:cart' %}">سبد خرید</a></li>
                    <li><a href="{% url 'IndexApp:about_us' %}">درباره ما</a></li>
                </ul>
            </div>

            <div class="col-12 col-md-12 col-lg-6">
                <hr class="d-lg-none">
                <img src="{{ site_info.logo.url }}" alt=""> {{ site_info.title }}
                <p>{{ site_info.short_description }}</p>
                <div class="row">
                    <div class="col-12 col-md-6 text-center p-2" id="encode43vfbb65gtabfb">
                        <div>7 روز هفته، 24 ساعت شبانه روز</div>
                        <div>پاسخگوی شما هستیم</div>
                        <div>{{ site_info.phone }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="py-2" id="copyright">
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-6" id="social-links">
                <span>ما را دنبال کنید</span>
                <a href="https://www.instagram.com/amir_baxxter/"><img src="{% static 'images/social/insta.png' %}" alt="insta"></a>
                <a href="https://m.facebook.com/profile.php/?id=100009090656940"><img src="{% static 'images/social/facebook.png' %}" alt="facebook"></a>
                <a href="https://x.com/amirbaxxter"><img src="{% static 'images/social/twitter.png' %}" alt="twitter"></a>
                <a href="https://m.youtube.com/channel/UCVAEn5meeV1EfAhxUncdCMw"><img src="{% static 'images/social/youtube.png' %}" alt="youtube"></a>
            </div>
            <div class="col-12 col-sm-6 text-sm-end pt-2 pt-sm-0">
                <span>کلیه حقوق و مادی معنوی محفوط است.</span>
            </div>
        </div>
    </div>
</section>

templates/infinite shop/partial/header.html
{% load static %}
<section id="header">
    <!-- Top NavBar -->
    <div id="encode4325436">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-4 text-center text-md-end" id="top-encode43vfbb65gtabfb">
                    <span> شماره تماس: {{ site_info.phone }}</span>
                </div>
            </div>
        </div>
    </div>
    <!-- /Top NavBar -->
    <!-- Search NavBar -->
    <div id="encode43254bvfb">
        <div class="container pt-1">
            <div class="row py-3 align-content-center">
                <div class="col-12 col-md-3 col-xl-2 text-center text-md-start pb-2" id="encode4326523bvfb">
                    <a href="{% url 'IndexApp:index' %}">
                        <img src="{{ site_info.logo.url }}" alt="">
                        <span>{{ site_info.title }}</span>
                    </a>
                </div>
                <div class="col-12 col-md-5 col-xl-6">
                    <form method="POST" action="{% url 'IndexApp:search' %}">
                        {% csrf_token %}
                        <div class="input-group">

                            <input {% if query %}value="{{ query }}"{% endif %}  name="query" type="text" class="form-control" placeholder="جستجو کنید">

                            <div class="input-group-append">
                                <button class="btn btn-outline-warning" type="submit">جستجو</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-12 col-md-4">
                    <div class="row">
                        <div class="col-5 col-md-9 col-lg-7 col-xl-6 ms-xl-auto ms-md-auto">
                            <a href="{% url 'CartApp:cart' %}">
                                <div class="btn btn-warning w-100"><i class="fa fa-shopping-cart"></i>&nbsp;<span
                                        class="d-lg-inline-block">سبد خرید</span>( <span
                                        id="cart-count">{{ cart.count }}</span> )
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /Search NavBar -->
    <!-- Main NavBar -->
    <div id="main-nav">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="droopmenu-navbar dmarrow-down droopmenu-horizontal dmpos-top dmfade">
                        <div class="droopmenu-inner">
                            <div class="droopmenu-header">
                                <a href="#" class="droopmenu-toggle"><i class="dm-burg"></i></a>
                                <span class="d-md-none">منوی فروشگاه</span>
                            </div>
                            <!-- Header Mega Menu-->
                            <div class="droopmenu-nav">
                                <div class="droopmenu-nav-wrap">
                                    <div class="droopmenu-navi">
                                        <ul class="droopmenu">
                                            <li>
                                                {% if request.user.is_authenticated %}
                                                    <a class="header-tabs"
                                                       href="{% url 'UserApp:profile' %}">پروفایل</a>
                                                {% else %}
                                                    <a class="header-tabs"
                                                       href="{% url 'UserApp:login' %}">ورود</a>
                                                {% endif %}
                                            </li>
                                            <li>
                                                <a class="header-tabs" href="{% url 'IndexApp:index' %}">صفحه نخست</a>
                                            </li>
                                            <li>
                                                <a class="header-tabs" href="{% url 'ProductsApp:product_list' %}">محصولات</a>
                                            </li>
                                            <li>
                                                <a class="header-tabs" href="{% url 'IndexApp:about_us' %}">درباره
                                                    ما</a>
                                            </li>

                                            {% if request.user.is_superuser %}
                                                <li>
                                                    <a target="_blank" class="header-tabs" href="/admin">پنل ادمین</a>
                                                </li>
                                            {% endif %}


                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <!-- /Header Menu Menu -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Main NavBar -->
</section>